### ISSUE TITLE
Rewrite cors.php in perl

### ISSUE THREAD

**Issue by vvidic** [perfsonar/pstracetree#1]
Since we don't install and use PHP for anything else in the project we should rewrite this script into perl too.

**Comment by okvittem** [comment]
Sure, this was only meant as an easy way for protyping.

**Comment by tonin** [comment]
@vvidic do you know if we don't already have replacement for that in graphs, perl-shared or toolkit package?

**Comment by vvidic** [comment]
On Wed, Nov 28, 2018 at 03:39:50PM +0000, Antoine Delvaux wrote:
> @vvidic do you know if we don't already have replacement for that in graphs, perl-shared or toolkit package?

Don't think so, but better double check with the US team.

Also this code acts as an open proxy so it is a bit dangerous,
maybe we check how the graphs access the MA data.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by tonin** [comment]
The `cors.php` is only needed by the `ls.html` page which is listing all the MA one can find in the global LS directory.  For the toolkit use, we don't need this LS listing because we'll always be looking at traces stored in the local Esmond.

So I'd suggest that we don't ship `ls.html` nor `cors.php` with the first version of the pstracetree packages.  Maybe we'll revisit this in the future, but then I think we should actually make the pstracetree package dependent on the graphs package and reuse the functionality and libraries contained therein (I'm thinking mostly about jquery).  I'll create a new issue to track that.
